### ISSUE TITLE
Ore Generation Settings on Non-Aether biomes

### ISSUE THREAD

**Issue by CarsonJF** [PolyhedralDev/BetterEnd-Public#68]
Being able to add ore generation and other options to non-aether biomes would allow even more flexibility with servers.

```
end:
  fall-to-overworld: true
  clouds:
    enable-clouds: true
    cloud-noise: 36
    cloud-height: 128
  ores:
    enable-ores: true
    ore-chance: 20
    weights:
      coal_ore: 40
      iron_ore: 25
      gold_ore: 10
      redstone_ore: 10
      lapis_ore: 10
      diamond_ore: 3
      emerald_ore: 2

```

This feature could replace endstone as its form of generation, and would allow plugin users to use more features without being tied to the aether biomes.
